// Code generated by mockery v2.12.3. DO NOT EDIT.

package oauthsdk

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	oauthsdk_git "gitlab.com/bavatech/architecture/software/libs/go-modules/oauthsdk.git"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: ctx
func (_m *Client) GetAccessToken(ctx context.Context) (*oauthsdk_git.JWT, error) {
	ret := _m.Called(ctx)

	var r0 *oauthsdk_git.JWT
	if rf, ok := ret.Get(0).(func(context.Context) *oauthsdk_git.JWT); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauthsdk_git.JWT)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewClientT interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t NewClientT) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
